#include "game/state.h"
#include "hw/input.h"
#include "hw/eeprom.h"
#include "hw/display.h"

int eeprom_value = 0;

void main_menu_load() {
	/* Set up i2c */
	I2C1CON = 0x0;
	/* I2C Baud rate should be less than 400 kHz, is generated by dividing
	the 40 MHz peripheral bus clock down */
	I2C1BRG = 0x0C2;
	I2C1STAT = 0x0;
	I2C1CONSET = 1 << 13; //SIDL = 1
	I2C1CONSET = 1 << 15; // ON = 1
	uint16_t temp = I2C1RCV; //Clear receive buffer
	do {
		i2c_start();
	} while(!i2c_send(1010000 << 1));

	i2c_send(0x00);

	i2c_send(0x32);

	i2c_send(0x4);

	i2c_stop();

	do {
		i2c_start();
	} while(!i2c_send(1010000 << 1));

	i2c_send(0x00);

	i2c_send(0x32);

	i2c_start();
	i2c_send(0xA1);

	eeprom_value = i2c_recv();
	i2c_stop();




}

/************************************************************
 * If the game is in the main menu and buttons are pressed  *
 * options are marked temporarily                           *
 * Written by Botan Botani                                  *
 ************************************************************/
void main_menu_update(int frame) {
	/* Play */
	if(input_get_btns_pressed() & BUTTON_ACTION){
		switch_state(STATE_SETUP_GAME, 0);
	}
}

void main_menu_draw() {
	char buffer[64];
	sprintf(buffer, "EEPROM: %d", eeprom_value);
	display_draw_text(buffer, 0, 0, 0);
}